name: Toons Frontend CI

on:
  push:
    branches: ['main']
env:
  DOCKER_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
  DOCKER_PW: ${{secrets.DOCKERHUB_PW}}
  DOCKER_REPO: ${{secrets.DOCKERHUB_USERNAME}}/toons

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Docker login
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PW

      - name: Extract Docker metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: limdev/toons
          tags: |
            type=sha,prefix={{branch}}-

      - name: Image Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{env.DOCKER_REPO}}:${{ steps.meta.outputs.version }}
            ${{env.DOCKER_REPO}}:latest
